### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by avinashdckap** [avinashdckap/Palli-Application#3]
User can be students, admin, dckap user and trainer

  - [x] User should be able to login using email and password
 - [x] on entering invalid password or email, error msg should be shown to the user
 - [x]  Password enter should be hidden by default and shown on clicking eye icon
 - [x] Forgot- password  link should be shown for the user 
 - [x] All password requirement should be shown while typing password
 
 
 **If you've completed the above user-stories, after creating PR, click the checkbox for completed one**

**Comment by avinashdckap** [comment]
@Parasuramandckap  @Ganeshdckap , design will not be included abve. while working on above userstories , work on the design as per figma

**Comment by avinashdckap** [comment]
Both of u work on seperate branches and create PR to "dev" branch

**Comment by ParasuramanA** [comment]
I have completed all the requirements you mentioned in the login page
